[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib.rs"

[[bin]]
name = "aoc-bin"
path = "src/main.rs"

[dependencies]
rayon = "1.7.0"
criterion = "0.4.0"
libmath = "0.2.1"

[[bench]]
name = "aoc"
harness = false
